/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.co.local.sample;

import jp.co.local.sample.basic.MainLoop;

public class Main {
    public static void main(String[] args) throws Throwable {
        MainLoop main = new MainLoop();
        main.run();

    }
}
