/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.co.local.sample;

import jp.co.local.sample.httpserver.Server;

public class Main {
    public static void main(String[] args) throws Throwable {
        Server main = new Server();
        main.run();

    }
}
