# version: "3"

services:
  app:
    container_name: vertx2
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "8085:8085"
    volumes:
      - type: bind
        source: "./"
        target: "/root/projects"
