/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.co.local.sample;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
